<a href="https://colab.research.google.com/github/RahulKumarOfficial/Deep_Learning_Basics/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [3]:
# Scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() # Get tensor back as python int

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                      [2, 3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([2, 3])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([4, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors

Why Random Tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data

`Start with random numbers -> Look at data -> Update Random numbers -> Look at data -> Update random numbers`

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [19]:
random_tensor[0]

tensor([0.5138, 0.3635, 0.6773, 0.1660])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
# Usually the datatype of tensor (unless explicitly defined) is
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [35]:
# Use torch.range
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [37]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [38]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)

In [42]:
float_32_tensor.dtype # This is the default type

torch.float32

Tensor datatypes is one of the big three errors you'll run into PyTorch and deep learning
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not in the right device

In [45]:
some_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # What datatype is the tensor (e.g. Float 32/16))
                            device=None, # Could be 'cuda' or 'cpu
                            requires_grad=False)

In [46]:
some_tensor

tensor([3., 6., 9.])

In [47]:
float_16_tensor = some_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)