<a href="https://colab.research.google.com/github/RahulKumarOfficial/Deep_Learning_Basics/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.tensor()`

In [3]:
# Scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
scalar.item() # Get tensor back as python int

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                      [2, 3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([2, 3])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([4, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors

Why Random Tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data

`Start with random numbers -> Look at data -> Update Random numbers -> Look at data -> Update random numbers`

In [37]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4, 30, 4, 2, 5, 20)

In [39]:
random_tensor[0]

tensor([[[[[[[1.2323e-01, 6.2686e-01, 9.5677e-01,  ..., 4.5629e-01,
              3.0080e-01, 7.6387e-01],
             [9.2796e-01, 9.3782e-01, 5.6299e-02,  ..., 3.2766e-02,
              7.1122e-01, 3.8322e-01],
             [6.9034e-01, 9.9178e-01, 2.3967e-01,  ..., 6.0510e-01,
              3.2181e-01, 7.4953e-01],
             [8.0626e-01, 5.0757e-01, 1.3728e-01,  ..., 2.7370e-01,
              4.5651e-01, 7.3116e-01],
             [2.8635e-01, 7.3605e-03, 9.8166e-01,  ..., 8.1865e-02,
              5.7871e-01, 3.1608e-01]],

            [[2.6000e-01, 8.3634e-01, 9.0014e-01,  ..., 7.0106e-01,
              7.7258e-01, 7.0765e-01],
             [8.8224e-01, 7.4932e-01, 1.1570e-01,  ..., 8.5749e-01,
              4.1311e-01, 8.0917e-01],
             [5.7945e-01, 6.3396e-01, 3.9737e-01,  ..., 9.6100e-01,
              5.0203e-01, 6.5108e-01],
             [5.7872e-01, 7.1045e-01, 3.9349e-01,  ..., 6.3127e-01,
              3.0054e-01, 1.7591e-01],
             [5.5460e-01, 7.0158e-0

In [40]:
random_tensor.ndim

8

In [33]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)