## Element Wise operation

x is a 2D numpy tensor

In [8]:
import numpy as np
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
y = np.array([[6, 78, 2, 34, 55],
              [11, 79, 342, 35, 14],
              [7, 80, 43, 36, 22]])
print(x.ndim, y.ndim)

2 2


In [10]:
def naive_relu(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()  # Avoid overwriting the input tensor
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x


naive_relu(x, y)

array([[ 11, 156,   4,  68,  55],
       [ 17, 158, 345,  70,  15],
       [ 14, 160,  47,  72,  24]])

Here is another way of doing it, but blazingly fast

In [12]:
z = x + y  # Element wise addition
print(z)

[[ 11 156   4  68  55]
 [ 17 158 345  70  15]
 [ 14 160  47  72  24]]
